apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-infomaniak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-webhook-infomaniak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cert-manager-webhook-infomaniak.selectorLabels" . | nindent 4 }}
  ipFamilyPolicy: PreferDualStack
