apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-infomaniak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-webhook-infomaniak.labels" . | nindent 4 }}
