apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: routinator
description: routinator helm chart for Kubernetes
type: application
version: 0.1.1
# image: nlnetlabs/routinator
appVersion: "v0.14.0"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/routinator
home: https://github.com/NLnetLabs/routinator
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
