apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: recyclarr
description: recyclarr helm chart for Kubernetes
type: application
version: 2.2.0
# image: ghcr.io/recyclarr/recyclarr
appVersion: "8.2.1"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/recyclarr
home: https://github.com/recyclarr/recyclarr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
