apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: prometheus-pve-exporter
description: prometheus-pve-exporter helm chart for Kubernetes
type: application
version: 2.0.6
# image: ghcr.io/prometheus-pve/prometheus-pve-exporter
appVersion: "3.6.0"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/prometheus-pve-exporter
home: https://github.com/prometheus-pve/prometheus-pve-exporter
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
