apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: bazarr
description: bazarr helm chart for Kubernetes
type: application
version: 2.1.0
# image: ghcr.io/home-operations/bazarr
appVersion: "1.5.5"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/bazarr
home: https://github.com/morpheus65535/bazarr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
