version: 2
updates:
# Check github actions are up to date.
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  assignees:
  - M0NsTeRRR
