apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.configPersistenceName" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  {{- with .Values.config.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.config.persistence.volumeName }}
  volumeName: {{ .Values.config.persistence.volumeName }}
  {{- end }}
  {{- with .Values.config.persistence.storageClass }}
  storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.config.persistence.size }}"