apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: homepage
description: homepage helm chart for Kubernetes
type: application
version: 1.1.0
# image: ghcr.io/gethomepage/homepage
appVersion: "v0.10.5"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/homepage
home: https://github.com/gethomepage/homepage
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
