apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: flaresolverr
description: flaresolverr helm chart for Kubernetes
type: application
version: 2.1.2
# image: flaresolverr/flaresolverr
appVersion: "v3.4.2"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/flaresolverr
home: https://github.com/FlareSolverr/FlareSolverr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
