apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: qbittorrent
description: qbittorrent helm chart for Kubernetes
type: application
version: 5.0.5
# image: ghcr.io/home-operations/qbittorrent
appVersion: "5.1.0"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/qbittorrent
home: https://github.com/qbittorrent/qBittorrent
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
