apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: jellyseerr
description: jellyseerr helm chart for Kubernetes
type: application
version: 1.0.0
# image: fallenbagel/jellyseerr
appVersion: "2.1.0"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/radarr
home: https://github.com/Fallenbagel/jellyseerr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
