apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: radarr
description: radarr helm chart for Kubernetes
type: application
version: 0.7.0
# image: ghcr.io/onedr0p/radarr
appVersion: "5.12.2"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/radarr
home: https://github.com/Radarr/Radarr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
