apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: kea-exporter
description: kea-exporter helm chart for Kubernetes
type: application
version: 0.2.7
# image: ghcr.io/mweinelt/kea-exporter
appVersion: "v0.7.0"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/kea-exporter
home: https://github.com/mweinelt/kea-exporter
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
