apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: prowlarr
description: prowlarr helm chart for Kubernetes
type: application
version: 2.6.2
# image: ghcr.io/home-operations/prowlarr
appVersion: "1.37.0"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/prowlarr
home: https://github.com/prowlarr/prowlarr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
