apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: prowlarr
description: prowlarr helm chart for Kubernetes
type: application
version: 0.1.8
# image: linuxserver/prowlarr
appVersion: "1.15.0"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/radarr
home: https://github.com/prowlarr/prowlarr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169